### PR TITLE
Ignore files under the `test/` directory

### PR DESCRIPTION
**Pull request by shoekstra**
Hi,

Needed to ignore files stored under the test folder to fix this:

```
Uploading zap            [2.3.0]
ERROR: Precondition Failed
Response:
 === Cookbook Compare errors found ===
 The source cookbook contains more files than your upload:
  - test/fixtures/cookbooks/test/attributes/default.rb
  - test/fixtures/cookbooks/test/files/cron
  - test/fixtures/cookbooks/test/files/file.txt
  - test/fixtures/cookbooks/test/metadata.rb
  - test/fixtures/cookbooks/test/recipes/apt_repos.rb
  - test/fixtures/cookbooks/test/recipes/cron.rb
  - test/fixtures/cookbooks/test/recipes/cron_d.rb
  - test/fixtures/cookbooks/test/recipes/directory.rb
  - test/fixtures/cookbooks/test/recipes/force.rb
  - test/fixtures/cookbooks/test/recipes/groups.rb
  - test/fixtures/cookbooks/test/recipes/init_d.rb
  - test/fixtures/cookbooks/test/recipes/iptables_d.rb
  - test/fixtures/cookbooks/test/recipes/notifies.rb
  - test/fixtures/cookbooks/test/recipes/sudoers_d.rb
  - test/fixtures/cookbooks/test/recipes/users.rb
  - test/fixtures/cookbooks/test/recipes/yum_repos.rb
  - test/fixtures/cookbooks/test/templates/source.erb
  - test/integration/apt_repos/default.rb
  - test/integration/cron/default.rb
  - test/integration/cron_d/default.rb
  - test/integration/directory/default.rb
  - test/integration/groups/default.rb
  - test/integration/init_d/default.rb
  - test/integration/iptables_d/default.rb
  - test/integration/notified/default.rb
  - test/integration/sudoers_d/default.rb
  - test/integration/unnotified/default.rb
  - test/integration/users/default.rb
  - test/integration/yum_repos/default.rb

 Source: https://supermarket.chef.io/api/v1/cookbooks/zap/versions/2.3.0/download
 =====================================
```

### CODE REVIEW

**Review by svanharmelen — APPROVED** [review]
Hi @shoekstra! Nice to "see you" and hope you are doing well 😄 PR looks good to me 👍🏻

**Comment by sbotman** [comment]
and its still in use... how cool is that... great to see you @shoekstra!

**Comment by shoekstra** [comment]
Magic, thanks for the quick reaction! And I hope you're both good too! 🙂

**Comment by svanharmelen** [comment]
In case needed or helpful I released `v0.7.4` 😏

**Pull request merged**
